---
common:
  mongo:
    uri: mongodb://mongo:27017
  production: false
  basic_auth:
    ladok: xyz
  tracing:
    addr: jaeger:4318
    type: jaeger
  queues:
    simple_queue:
      ladok_sign:
        name: sign
      ladok_add_signed:
        name: add_signed
      ladok_del_signed:
        name: del_signed
      ladok_validate:
        name: validate
      ladok_persistent_save:
        name: persistent_save

  
datastore:
  api_server:
    addr: :8080
  rpc_server: 
    addr: datastore:8090
  
mock_as:
  api_server:
    addr: :8080
  datastore_url: http://vc_datastore:8080